database:


server:

nemesis:
  # mode -- partition, clock, pause, kill, None
  mode: "pause"
  # when mode is partition, partition_method should be set
  # partition_method:
  #   one: randomly select one of the nodes
  #   majority: select the first floor half of the nodes
  #   majorities_ring: select some groups by a great algorithm
  #   minority-third: select the first one-third floor of the nodes
  #   primaries: separate all nodes with each other
  partition_method: "majorities_ring"
  # when mode is clock. step should be set
  # It`s the time of the step the clock will be changed and the unit is seconds
  #step: 60

checker:
  # models -- cas-register, mutex, register
  models: "cas-register"
  # algos -- competition, wgl, linear
  algos: "competition"